name: 'Synopsys Unified'
description: 'Scan using synopsys tools'
author: 'Synopsys Inc'
inputs:
  data1:
    description: 'Your Data1'
    required: true
  data2:
    description: 'Your Data1'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
