name: Release new action version
on:
#   release:
#     types: [releas]
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Bump Version'
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}
permissions:
  contents: write

jobs:
  update_tag:
#     name: Update the major tag to include the ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }} changes
#     environment:
#       name: releaseNewActionVersion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 12.x
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Update the version
        run: |
          echo ${{ env.TAG_NAME }}
          npm ci
          npm version ${{ env.TAG_NAME }}
      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.js*
#       - name: common code
#         run: |  
#           git config --global user.name "kishorikumar"
#           git config --global user.email "kishori@sysnopsys.com"
#           git add -A
#           git commit -a -m "version change"
#           git push origin HEAD:master
#     - name: Update the ${{ env.TAG_NAME }} tag
#       uses: actions/publish-action@v0.1.0
#       with:
#         source-tag: ${{ env.TAG_NAME }}
#         slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
